name: one_social_suite
description: "Write once. Share smarter. A private social command center."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.2.2
  share_plus: ^13.1.0
  url_launcher: ^6.3.2
  local_auth: ^2.3.0
  shared_preferences: ^2.5.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  image_path: "assets/images/app_icon.png"
  ios: true
  android: true
  remove_alpha_ios: true
  background_color_ios: "#000000"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/app_icon.png"
